kitti_to_ros2bag_node:
  ros__parameters:
    use_ground_truth: true
    kitti_path: "/home/ubuntu/data/kitti/2011_10_03"
    data_folder: "2011_10_03_drive_0027_sync"
    # this folder shall have image_00, image_01, image_02, image_03, oxts, and velodyne_points
    calib_folder: ""
    # by default the calibration files are under kitti_path. If you put the calibration files into
    # a different folder, then you will have to change it.
    # The folder shall have calib_cam_to_cam.txt, calib_imu_to_velo.txt, and calib_velo_to_cam.txt.
    # if not, the camera_info won't be outputted
    dirs: ["image_02", "oxts", "velodyne_points", "ground_truth"] # dirs that you want to publish
    # dirs: ["image_00"] this will output image_00 data only
